---
- hosts: ansible
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Create a deployment
    command: kubectl apply -f /opt/docker/jenkins-kubernetes-pipeline/myapp.yaml
