---
- hosts: ansible
  connection: local
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Clear
    file:
      path: "/opt/docker/jenkins-ansible-kubernetes-pipeline"
      state: absent
  - name: clone repository
    git:
      repo: https://github.com/ahmedmahfoudhi/jenkins-ansible-kubernetes-pipeline.git
      dest: /opt/docker/jenkins-ansible-kubernetes-pipeline
      clone: yes
      update: yes
  - name: login to Dockerhub
    docker_login:
      username: mahfoudhi
      password: "{{dockerhub_password}}"
  - name: Build docker image
    docker_image:
      build:
        path: "/opt/docker/jenkins-ansible-kubernetes-pipeline/backend-app"
      name: myapp
      tag: latest
      source: build
  - name: Push docker image
    docker_image:
      name: myapp
      repository: mahfoudhi/myapp
      tag: latest
      push: yes
      source: local
